config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' },
                     skip: [:registrations, :passwords]

  root 'tasks#index'

  resources :tasks do
    resources :sub_tasks, except: [:new, :show]
  end
end

app/models/sub_task.rb
class SubTask < ActiveRecord::Base
  belongs_to :task

  validates :description, presence: true

  def completed!(value)
    update_attribute(:completed, value)
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  enum kind: { particular: 0, common: 1 }

  belongs_to :user
  has_many :sub_tasks

  validates :description, :kind, presence: true
  validates :kind, inclusion: { in: Task.kinds.keys }

  scope :by_user, ->(value) { where(user_id: value) }
  scope :not_user, ->(value) { where.not(user_id: value) }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController
  before_action :set_task, except: :destroy
  before_action :set_sub_task, only: [:update, :destroy]

  def index
    render json: @task.sub_tasks.order(:description), root: false
  end

  def create
    @sub_task = SubTask.new(create_params)

    if @sub_task.save
      render json: @sub_task
    else
      render json: { errors: @sub_task.errors.full_messages }, status: :bad_request
    end
  end

  def update
    if @sub_task && @sub_task.completed!(update_params[:completed])
      Updater::Task.new(@task).mark_as_completed!

      render json: { message: t('messages.updated', scope: :success) }
    else
      render json: { message: t('messages.not_updated', scope: :errors) }, status: :bad_request
    end
  end

  def destroy
    if @sub_task && @sub_task.destroy
      render json: { message: t('messages.destroyed', scope: :success) }
    else
      render json: { message: t('messages.not_destroyed', scope: :errors) }, status: :conflict
    end
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end

  def set_sub_task
    @sub_task = SubTask.find_by(id: params[:id])
  end

  def create_params
    params.require(:sub_task).permit(:description).merge(task_id: @task.id)
  end

  def update_params
    params.require(:sub_task).permit(:id, :completed)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, except: [:index, :new, :create]

  def index
    @tasks = Task.by_user(current_user.id) + Task.not_user(current_user.id).common
  end

  def new
    @task = Task.new
  end

  def edit
    @sub_task = SubTask.new(task_id: @task.id)

    if current_user != @task.user
      redirect_to tasks_url, notice: 'You do not have permission to edit Tasks from other users .'
    end
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to edit_task_url(@task), notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_url, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :kind).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sub_tasks/_form.html.erb
<%= simple_form_for(@sub_task, url: task_sub_tasks_path(task_id: @sub_task.task_id), remote: true) do |f| %>
  <%= f.input :description %>
<% end %>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :id %>
  <%= f.input :description %>
  <%= f.input :kind, collection: Task.kinds.symbolize_keys.keys,
                     include_blank: false,
                     selected: f.object.kind %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
<h2>Editing Task</h2>
<%= render 'form' %>

<section>
  <h3>Sub Tasks</h3>
  <ul id='sub_tasks'></ul>
  <div id='sub_task_form'>
    <%= render 'sub_tasks/form' %>
  </div>
</section>

<%= link_to 'Back', tasks_path %>

<script id="sub-task-template" type="text/x-handlebars-template">
  <li>
    {{#if completed }}
      <input type="checkbox" checked="checked" data-sub-task-id="{{id}}">
    {{else}}
      <input type="checkbox" data-sub-task-id="{{id}}">
    {{/if}}

    <span>{{description}}</span>
    <button type="remove" data-sub-task-id="{{id}}">Remove</button>
  </li>
</script>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<%= link_to 'New Task', new_task_path %>

<table>
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.completed %></td>
        <td><%= task.description %></td>
        <td><%= task.kind %></td>

        <% if current_user == task.user %>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
          <td><%= link_to 'Show', task_path(task) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<h2>Show Task</h2>

<p>User: <%= @task.user.name %></p>
<p>Description: <%= @task.description %></p>
<p>Kind: <%= @task.kind %></p>

<h3>Sub Tasks</h3>
<% @task.sub_tasks.each do |sub_task| %>
  <li><%= sub_task.description %></li>
<% end %>

<%= link_to 'Back', tasks_path %>